version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "app.run:bootstrap()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/src'
    ports:
      - '8000:8000'
