version: '2'

services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    env_file:
      - '.env'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    stdin_open: true
    tty: true
    env_file:
      - '.env'
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
            --access-logfile -
            --reload
            "app.app:create_app()"
    volumes:
      - '.:/src'
    ports:
      - '8000:8000'

volumes:
  postgres:
  redis:
